---
# tasks file for apt_source

- name: Include default variables
  include_vars: defaults.yml

- include: apt-key.yml
  when: apt_source_config.0.source is defined
    and not apt_source_config.0.source.startswith("ppa:")

- include: apt-repo.yml

- include: apt-pin.yml
